// ===== Phase 4：API 错误码目录（machine-readable，稳定 ASCII 常量）=====
// 设计约定：
//   1. API 响应增量兼容：保留原有 `error` 字段（中文原文），新增 `code` 字段
//   2. code 语义不合并：语义不同的错误使用不同 code
//   3. EN/ZH 展示文案在 messages/{en,zh}.json 的 `apiErrors` 命名空间（单一数据源）
//   4. 本文件只定义常量，供 API route / 前端 / 测试共同引用
//
// 分类：
//   AUTH_*        鉴权
//   *_INVALID / *_REQUIRED / *_NOT_CONFIGURED 等  参数与请求校验
//   *_NOT_FOUND / *_EXISTS / *_FAILED             资源与持久化
//   PLAN_* / *_LIMIT_* / QUOTA_* / *_COOLDOWN     套餐、配额与频控
//   UPSTREAM_* / *_NOT_CONFIGURED / PAYMENT_*     上游依赖、支付、邮件
//   CRAWL_*                                        内容抓取（既有 code，保持原样）

export const API_ERROR_CODES = {
  // ---- 鉴权 ----
  AUTH_REQUIRED: "AUTH_REQUIRED",

  // ---- 参数与请求校验 ----
  INVALID_JSON: "INVALID_JSON",
  BAD_REQUEST: "BAD_REQUEST", // seo 系 route 既有 code，保留原值
  DOMAIN_REQUIRED: "DOMAIN_REQUIRED",
  INVALID_DOMAIN: "INVALID_DOMAIN",
  MISSING_DOMAIN: "MISSING_DOMAIN",
  MISSING_ID: "MISSING_ID",
  INVALID_ID: "INVALID_ID",
  INVALID_PROJECT_ID: "INVALID_PROJECT_ID",
  INVALID_KEYWORD_ID: "INVALID_KEYWORD_ID",
  INVALID_GROUP_ID: "INVALID_GROUP_ID",
  INVALID_DAYS: "INVALID_DAYS",
  NAME_REQUIRED: "NAME_REQUIRED",
  NAME_TOO_LONG: "NAME_TOO_LONG",
  URL_REQUIRED: "URL_REQUIRED",
  KEYWORD_REQUIRED: "KEYWORD_REQUIRED",
  DEVICE_INVALID: "DEVICE_INVALID",
  EMAIL_INVALID: "EMAIL_INVALID",
  PLAN_PARAM_INVALID: "PLAN_PARAM_INVALID",
  PAYMENT_CHANNEL_INVALID: "PAYMENT_CHANNEL_INVALID",
  OUT_TRADE_NO_REQUIRED: "OUT_TRADE_NO_REQUIRED",
  MONEY_INVALID: "MONEY_INVALID",
  AUTOMATION_TYPE_INVALID: "AUTOMATION_TYPE_INVALID",
  REPORT_TYPE_INVALID: "REPORT_TYPE_INVALID",
  TITLE_REQUIRED: "TITLE_REQUIRED",
  DATA_JSON_REQUIRED: "DATA_JSON_REQUIRED",
  DAILY_REFRESH_ENABLED_INVALID: "DAILY_REFRESH_ENABLED_INVALID",
  WEEKLY_REPORT_DAY_INVALID: "WEEKLY_REPORT_DAY_INVALID",

  // ---- 资源与持久化 ----
  PROJECT_NOT_FOUND: "PROJECT_NOT_FOUND",
  PROJECT_EXISTS: "PROJECT_EXISTS",
  PROJECT_QUERY_FAILED: "PROJECT_QUERY_FAILED",
  PROJECT_CREATE_FAILED: "PROJECT_CREATE_FAILED",
  PROJECT_DELETE_FAILED: "PROJECT_DELETE_FAILED",
  COMPETITOR_NOT_FOUND: "COMPETITOR_NOT_FOUND",
  COMPETITOR_EXISTS: "COMPETITOR_EXISTS",
  SELF_COMPETITOR: "SELF_COMPETITOR",
  KEYWORD_NOT_FOUND: "KEYWORD_NOT_FOUND",
  KEYWORD_NOT_IN_GROUP: "KEYWORD_NOT_IN_GROUP",
  TRACKING_NOT_FOUND: "TRACKING_NOT_FOUND",
  TRACKING_DUPLICATE: "TRACKING_DUPLICATE",
  GROUP_NOT_FOUND: "GROUP_NOT_FOUND",
  REPORT_NOT_FOUND: "REPORT_NOT_FOUND",
  AUDIT_NOT_FOUND: "AUDIT_NOT_FOUND",
  ORDER_NOT_FOUND: "ORDER_NOT_FOUND",
  SETTINGS_NOT_FOUND: "SETTINGS_NOT_FOUND",

  // ---- 套餐 / 配额 / 频控 ----
  PLAN_REQUIRED: "PLAN_REQUIRED",
  PLAN_DOWNGRADE_NOT_ALLOWED: "PLAN_DOWNGRADE_NOT_ALLOWED",
  PLAN_PRICE_NOT_CONFIGURED: "PLAN_PRICE_NOT_CONFIGURED",
  AUDIT_RATE_LIMITED: "AUDIT_RATE_LIMITED",
  AUDIT_COOLDOWN: "AUDIT_COOLDOWN",
  AUDIT_IN_PROGRESS: "AUDIT_IN_PROGRESS",
  BACKLINK_COOLDOWN: "BACKLINK_COOLDOWN",
  QUOTA_EXCEEDED: "QUOTA_EXCEEDED",
  FREE_QUOTA_EXCEEDED: "FREE_QUOTA_EXCEEDED",
  // billing-errors.ts 既有 code（保持一致，纳入统一目录）
  FEATURE_NOT_AVAILABLE: "FEATURE_NOT_AVAILABLE",
  PLAN_LIMIT_REACHED: "PLAN_LIMIT_REACHED",
  PROJECT_LIMIT_REACHED: "PROJECT_LIMIT_REACHED",
  KEYWORD_LIMIT_REACHED: "KEYWORD_LIMIT_REACHED",
  AUDIT_DAILY_LIMIT_REACHED: "AUDIT_DAILY_LIMIT_REACHED",
  COMPETITOR_LIMIT_REACHED: "COMPETITOR_LIMIT_REACHED",
  KEYWORD_GROUP_LIMIT_REACHED: "KEYWORD_GROUP_LIMIT_REACHED",

  // ---- 上游依赖 / 支付 / 邮件 / 系统 ----
  UPSTREAM_ERROR: "UPSTREAM_ERROR",
  DATAFORSEO_NOT_CONFIGURED: "DATAFORSEO_NOT_CONFIGURED",
  YAOLIPAY_NOT_CONFIGURED: "YAOLIPAY_NOT_CONFIGURED",
  PAYMENT_CREATE_FAILED: "PAYMENT_CREATE_FAILED",
  PAYMENT_FAILED: "PAYMENT_FAILED",
  REFUND_FAILED: "REFUND_FAILED",
  PAYMENT_DEMO_DISABLED: "PAYMENT_DEMO_DISABLED",
  PAYMENT_TEST_MODE_FORBIDDEN: "PAYMENT_TEST_MODE_FORBIDDEN",
  REFUND_DEMO_DISABLED: "REFUND_DEMO_DISABLED",
  REFUND_NOT_ALLOWED: "REFUND_NOT_ALLOWED",
  REFUND_AMOUNT_EXCEEDED: "REFUND_AMOUNT_EXCEEDED",
  RESEND_NOT_CONFIGURED: "RESEND_NOT_CONFIGURED",
  SEND_FAILED: "SEND_FAILED",
  ADMIN_CLIENT_UNAVAILABLE: "ADMIN_CLIENT_UNAVAILABLE",
  VERIFY_READ_FAILED: "VERIFY_READ_FAILED",
  NO_CONTENT_CHECKS: "NO_CONTENT_CHECKS",
  NO_TRACKING_KEYWORDS: "NO_TRACKING_KEYWORDS",

  // ---- GSC（Google Search Console 第一方数据，P0-02-E）----
  GSC_NOT_CONFIGURED: "GSC_NOT_CONFIGURED",
  GSC_NOT_CONNECTED: "GSC_NOT_CONNECTED",
  GSC_AUTH_REQUIRED: "GSC_AUTH_REQUIRED",
  GSC_QUOTA_EXCEEDED: "GSC_QUOTA_EXCEEDED",
  GSC_PROPERTY_NOT_FOUND: "GSC_PROPERTY_NOT_FOUND",
  GSC_PROVIDER_ERROR: "GSC_PROVIDER_ERROR",

  // ---- AI Search（P0-03-B，DataForSEO AI Optimization）----
  AI_SEARCH_INVALID_MODEL: "AI_SEARCH_INVALID_MODEL",
  AI_SEARCH_UNSUPPORTED_PLATFORM: "AI_SEARCH_UNSUPPORTED_PLATFORM",
  AI_SEARCH_PROVIDER_ERROR: "AI_SEARCH_PROVIDER_ERROR",
  AI_SEARCH_PROVIDER_QUOTA: "AI_SEARCH_PROVIDER_QUOTA",
  AI_SEARCH_BILLING_ISSUE: "AI_SEARCH_BILLING_ISSUE",
  AI_SEARCH_NOT_CONFIGURED: "AI_SEARCH_NOT_CONFIGURED",
  AI_SEARCH_NOT_AVAILABLE_ON_PLAN: "AI_SEARCH_NOT_AVAILABLE_ON_PLAN",

  // ---- 内容抓取（content/check 既有 code，contract 不变）----
  CRAWL_TIMEOUT: "TIMEOUT",
  CRAWL_INVALID_URL: "INVALID_URL",
  CRAWL_HTTP_ERROR: "HTTP_ERROR",
  CRAWL_FAILED: "UNKNOWN",
} as const;

export type ApiErrorCode = typeof API_ERROR_CODES[keyof typeof API_ERROR_CODES];

/** 全部合法 code 集合（测试用：唯一性校验） */
export const ALL_API_ERROR_CODES: readonly string[] = Object.values(API_ERROR_CODES);
